### ISSUE TITLE
Fix MSCG-Net dependencies

### ISSUE THREAD

**Issue by henrylao** [akailany/Pattern-Segmentation-in-Aerial-Agricultural-Images#9]
Overview
---
The provided repository is a useful headstart for development but is out-of-date. Breakages were observed when attempting to clone and train using the provided repository

* __Original MSCG-Net Repository__: https://github.com/samleoqh/MSCG-Net

* __Our MSCG-Net Repository__: [Add link to repo here]()

Fix for the following
- [x] requirements.txt
- [x] `lib.*` referring to MSCG's internal API

Verification working for 
- [x] Google Colab
- [x] Local

**Comment by ManishKakarla** [comment]
# not a fix but need to check
- some modules (lib) are not imported correctly ,Need to look at importing the modules
[https://codeolives.com/2020/01/10/python-reference-module-in-parent-directory/](https://codeolives.com/2020/01/10/python-reference-module-in-parent-directory/) 
[https://xxx-cook-book.gitbooks.io/python-cook-book/content/Import/import-from-parent-folder.html](https://xxx-cook-book.gitbooks.io/python-cook-book/content/Import/import-from-parent-folder.html)

**Comment by henrylao** [comment]
Status Update 11/16
---
Updated to new updates at: https://github.com/PradeepG00/P3-SemanticSegmentation
- Currently still experiencing pathing issues

**Comment by henrylao** [comment]
Resolved dependency issues for installing and running via command line when using in Google Colab: https://github.com/PradeepG00/P3-SemanticSegmentation/tree/feature/py39-dependency-fix

Not verified working for local deployments

**Comment by henrylao** [comment]
Overview
---
- Notebook reflecting the current state of the issue: https://colab.research.google.com/drive/1R5bmswERYFjyL7MJZdgCjrxpDfrMTlN7?usp=sharing
- It appears that there is missing data -- specifically, the training script is not properly preprocessing the images

**Comment by henrylao** [comment]
# 11/24 Update
Applied changes to resolve dependency issues with documentation of necessary configurations and verification of training and checkpointing working: https://github.com/PradeepG00/P3-SemanticSegmentation/pull/1

![image.png](https://images.zenhubusercontent.com/6160c9f33ea2f2626bc3e05d/161342e6-0e48-489a-8dbd-ebea857741a0)
